### ISSUE TITLE
RangeError: Source is too large

### ISSUE THREAD

**Issue by ktjd123** [amishshah/prism-media#20]
#### Issue:

I had this issue when I use with discord.js v12.

```js
0|index  | RangeError: Source is too large
0|index  |     at Uint16Array.set (<anonymous>)
0|index  |     at OpusScript.encode (C:\Users\com\Desktop\build\node_modules\opusscript\index.js:51:16)
0|index  |     at Encoder._encode (C:\Users\com\Desktop\build\node_modules\prism-media\src\opus\Opus.js:54:25)
0|index  |     at Encoder._transform (C:\Users\com\Desktop\build\node_modules\prism-media\src\opus\Opus.js:137:30)
0|index  |     at Encoder.Transform._read (_stream_transform.js:190:10)
0|index  |     at Encoder.Transform._write (_stream_transform.js:178:12)
0|index  |     at doWrite (_stream_writable.js:410:12)
0|index  |     at writeOrBuffer (_stream_writable.js:394:5)
0|index  |     at Encoder.Writable.write (_stream_writable.js:294:11)
0|index  |     at VolumeTransformer.ondata (_stream_readable.js:689:20)
0|index  |     at VolumeTransformer.emit (events.js:189:13)
0|index  |     at VolumeTransformer.EventEmitter.emit (domain.js:459:23)
0|index  |     at addChunk (_stream_readable.js:284:12)
0|index  |     at readableAddChunk (_stream_readable.js:265:11)
0|index  |     at VolumeTransformer.Readable.push (_stream_readable.js:220:10)
0|index  |     at VolumeTransformer.Transform.push (_stream_transform.js:151:32)
```

#### Steps to reproduce:

I think it happens when repeat request happens.

#### Further details:
- Operating System: macOS 10.14.3 (Happens in mac, windows)
- Node.js version: v10.15.3
- Commit I'm using: 

Thank you. Always appreciate your work.

**Comment by amishshah** [comment]
Thanks for the report, could you send me the code you're using to play the file?

**Comment by ktjd123** [comment]
@amishshah Thank you for reply.

```js
import Notification from "../model/Notification";
import FollowChannel from "../model/FollowChannel";
import path from "path";
import fs from "fs";

const resPath = path.join(__dirname, "../res/");

export default async bot => {
  let notification = await Notification.findOne({ token: bot.token });
  if (!notification) {
    return;
  }
  try {
    if (notification.message) {
      const textChannel = bot.channels.get(notification.channel);
      if (!textChannel) {
        const removedChannel = await FollowChannel.findOne({
          channel: notification.channel
        });
        await removedChannel.remove();
        return;
      }
      bot.channels.get(notification.channel).send(notification.message);
    }

    if (notification.voice === "" || notification.voice === undefined) {
      return;
    }

    let voiceChannel = bot.channels.get(notification.voiceChannel).connection;
    let dispatcher = undefined;

    if (notification.type === "boss") {
      dispatcher = voiceChannel.play(
        path.join(resPath, notification.voice + ".mp3"),
        { passes: 3 }
      );
    } else {
      dispatcher = voiceChannel.play(
        path.join(resPath, "tts", notification.voice + ".mp3"),
        { passes: 3 }
      );

      dispatcher.on("end", () => {
        fs.unlink(
          path.join(resPath, "tts", notification.voice + ".mp3"),
          err => {
            if (err) return console.error("TTS REMOVE ERROR");
          }
        );
      });
    }

    dispatcher.on("error", err => {
      console.error(err);
    });
  } catch (e) {
    throw e;
  } finally {
    await notification.remove();
  }

  return;
};
```

this is full code of notifier function and it's called every 5seconds.
