### ISSUE TITLE
prism-media/src/transcoders/ffmpeg/Ff

### ISSUE THREAD

**Issue by GamingonTour** [amishshah/prism-media#37]
Hi there,
my BOT gives me the following error.

at new VoiceConnection (/root/Musik/node_modules/discord.js/src/client/voice/VoiceConnection.js:46:18)                   
at Promise (/root/Musik/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:63:22)                            
at new Promise (<anonymous>)                                                                                             
at ClientVoiceManager.joinChannel (/root/Musik/node_modules/discord.js/src/client/voice/ClientVoiceManager.js:45:12)     
at VoiceChannel.join (/root/Musik/node_modules/discord.js/src/structures/VoiceChannel.js:130:30)                     
 at Object.module.exports.addToQueue (/root/Musik/tools.js:93:51)                                                         
at search (/root/Musik/commands/play.js:148:27)                                                                          
at /root/Musik/node_modules/youtube-search/index.js:106:14                                                               process._tickCallback (internal/process/next_tick.js:68:7) 

best regards

**Comment by amishshah** [comment]
Can you please post the error again? You have not included the error itself.

**Comment by amishshah** [comment]
Closing due to inactivity
