### ISSUE TITLE
not sure if this is important, but...

### ISSUE THREAD

**Issue by YinglunQ** [amishshah/prism-media#49]
#### Issue:

So I am using this package for a discordjs bot to play music. And sometimes (when i pause the streamDispatcher for a while, and resume), I get the following errors:

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at StreamDispatcher.write (_stream_writable.js:292:11)
    at Encoder.ondata (_stream_readable.js:717:22)
    at Encoder.emit (events.js:314:20)
    at addChunk (_stream_readable.js:307:12)
    at readableAddChunk (_stream_readable.js:282:9)
    at Encoder.push (_stream_readable.js:221:10)
    at Encoder.push (_stream_transform.js:166:32)
    at Encoder._transform (/usr/app/node_modules/prism-media/src/opus/Opus.js:144:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```
```
TypeError: Cannot read property 'length' of null
    at Encoder._transform (/usr/app/node_modules/prism-media/src/opus/Opus.js:142:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) Promise {
  <rejected> TypeError: Cannot read property 'length' of null
      at Encoder._transform (/usr/app/node_modules/prism-media/src/opus/Opus.js:142:25)       
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
}
```

#### Steps to reproduce:

Sometimes it happens randomly when playing music; other times is when pausing the `StreamDispatcher` for a while then resume using `Discord.js`.

#### Further details:
- Operating System:
- Node.js version:
- Commit I'm using:

**Comment by amishshah** [comment]
This is a Discord.js issue so I will close the issue. In the meantime, you can check out the new voice library [@discordjs/voice](https://github.com/discordjs/voice/) to see if this helps!
