### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by amitojsingh366** [amishshah/prism-media#51]
```
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Emitted 'error' event on FFmpeg instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at FFmpeg.onerror (_stream_readable.js:755:7)
    at FFmpeg.emit (events.js:314:20)
    at Socket.processError (/Volumes/Extreme SSD/Projects/Discord_Bots/music_bot/node_modules/prism-media/src/core/FFmpeg.js:64:40)
    at Socket.emit (events.js:314:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:424:5)
    at onwrite (_stream_writable.js:445:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:681:5) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```
I am unable to use this library. I get the error above.

**Comment by amishshah** [comment]
Please post a reproducible code sample if you would like support for this issue.

**Comment by amitojsingh366** [comment]
@amishshah afaik this error occurred when i tried running prism-media on two projects at the same time on the same machine. Now i only use it for one project currently and it works fine
