### ISSUE TITLE
The compressed data passed is corrupted

### ISSUE THREAD

**Issue by rowisahub** [amishshah/prism-media#53]
#### Issue:

I'm trying to get a audio packet from a user, and when i try and run my code it shows up as

[the picture](https://rowisabeast.com/image/ortolfqr.png)

or

```
/home/row/alexa_bot_testing/node_modules/prism-media/src/opus/Opus.js:64
    return this.encoder.decode(buffer, Opus.name === 'opusscript' ? null : this._options.frameSize);
                        ^

TypeError: The compressed data passed is corrupted
    at Decoder._decode (/home/row/alexa_bot_testing/node_modules/prism-media/src/opus/Opus.js:64:25)
    at Decoder._transform (/home/row/alexa_bot_testing/node_modules/prism-media/src/opus/Opus.js:203:20)
    at Decoder.Transform._read (_stream_transform.js:205:10)
    at Decoder.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Decoder.Writable.write (_stream_writable.js:303:10)
    at Readable.ondata (_stream_readable.js:719:22)
    at Readable.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
```

I'm running this for a discord bot, it might be a discord thing but wanted to check first

node version - v14.15.1
npm version - 6.14.8
prism-media version - 1.2.3

**Comment by FHGDev** [comment]
Getting this issue also.

**Comment by FHGDev** [comment]
Hey! I was able to solve this issue by messing around with the Discord.js VoiceConnection play method.

All you have to do (all I did) was change the type to "unknown"

My code:

```js
connection.play(stream, { type: "unknown" })
```

**Comment by rowisahub** [comment]
> ```js
> connection.play(stream, { type: "unknown" })
> ```

Just wondering how this works. I'll try it the minute i can. Cause when you usually want the bot to me silent you make/call a silence function. 

Like i said i'll try it soon. But im getting this error well receiving audio from discord. And only when the user is on the website.

**Comment by FHGDev** [comment]
OH! Sorry, I thought you were trying to play audio. That's what I was trying to do.

**Comment by amishshah** [comment]
This sounds like a Discord.js issue. Unfortunately, voice receive is documented as unsupported because we lack official documentation for it. I'm closing the issue as it isn't suited for this repo.
